# Base Variables
title: Instituto del Ambiente
subtitle: Estudios Superiores en Medio Ambiente y Recursos Naturales
url: https://institutodelambiente.netlify.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# URLs
permalink: pretty

# Collections
collections:
  careers:
    output: true
    permalink: /instituto/:collection/:name
  teachers:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - src
  - tailwind.js